services:
  postgres:
    image: postgres:16-alpine
    container_name: inventory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: product_inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inventory-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/product_inventory_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      DEF_ADMIN_USERNAME: admin@inventory.com
      DEF_ADMIN_PASSWORD: Admin@123
    networks:
      - inventory-network

volumes:
  postgres_data:

networks:
  inventory-network:
    driver: bridge
